[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ALWAYS"
healthcheckEnabled = false

[deploy.envs]
PYTHON_VERSION = "3.11.7"
TZ = "Asia/Jakarta"
