[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[deploy.envs]
PYTHON_VERSION = "3.11.7"

[[services]]
name = "bot"
persistent = true
